site_name: chat
site_description: Simple chat
repo_url: https://github.com/RootenberG/mini-chat
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/RootenberG">RootenberG</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
